namespace: default

frontend:
  image: srvpndy/frontend:49dfbff
  port: 80
  servicePort: 80
  nodePort: 30080

backend:
  image: srvpndy/backend:49dfbff
  port: 5001
  servicePort: 5001
  corsOrigin: http://mega.local

mongo:
  image: mongo:7
  port: 27017
  username: admin
  password: secure123
  database: userdb
  storage: 1Gi
