services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure123

  backend:
    image: srvpndy/backend:e79f21b
    container_name: backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: userdb
      MONGO_AUTH_SOURCE: admin
      MONGO_USER: admin
      MONGO_PASSWORD: secure123
      MONGO_URI: mongodb://admin:secure123@mongo:27017/myapp?authSource=admin
      JWT_SECRET: this-is-a-long-random-secret
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:5001
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
