config:
  service: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

  inputs: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  outputs: |
    [OUTPUT]
        Name        loki
        Match       *
        Host        loki-gateway.logging.svc.cluster.local
        Port        80
        Labels      job=fluentbit
        Auto_Kubernetes_Labels on