apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.storage }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.mongo.replicaCount }}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image }}:{{ .Values.mongo.tag }}"
          imagePullPolicy: {{ .Values.mongo.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.mongo.port }}

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD

          resources:
            requests:
              cpu: {{ .Values.mongo.resources.requests.cpu }}
              memory: {{ .Values.mongo.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mongo.resources.limits.cpu }}
              memory: {{ .Values.mongo.resources.limits.memory }}

          volumeMounts:
            - name: mongo-data
              mountPath: {{ .Values.mongo.mountPath }}

          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: {{ .Values.mongo.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mongo.livenessProbe.periodSeconds }}

          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: {{ .Values.mongo.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mongo.readinessProbe.periodSeconds }}

      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongo
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
