apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_USER: {{ .Values.apps.backend.secrets.MONGO_USER | quote }}
  MONGO_PASSWORD: {{ .Values.apps.backend.secrets.MONGO_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.apps.backend.secrets.JWT_SECRET | quote }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.password | quote }}