{{- range $name, $app := .Values.apps }}
{{- if and $app.enabled $app.monitoring $app.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $name }}-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ $name }}

  namespaceSelector:
    matchNames:
      - {{ $.Values.namespace }}

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
{{- end }}
{{- end }}