# mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: thedeva
type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: secure123